import initScrollSuave from "./modules/scroll-suave.js";
import initAnimacao from "./modules/scroll-animacao.js";
import initAccordion from "./modules/accordion-animacao.js";
import initTabMenu from "./modules/tab-nav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initAnimaisFetch from "./modules/animais-fetch.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initScrollSuave();
initAnimacao();
initAccordion();
initModal();
initTabMenu();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initAnimaisFetch();
initFetchBitcoin();
